[preface]
== Lời nói đầu

Tháng 1/2018 tôi đã bắt đầu chuẩn bị một khóa học lập trình hướng đến nhóm sinh viên chưa có kinh nghiệm gì về lập trình. Tôi muốn dùng ngôn ngữ Julia song phát hiện thấy chưa có sách nào với mục đích học lập trình với Julia như ngôn ngữ đầu tiên. Có những bài hướng dẫn tuyệt vời giúp giải thích những khái niệm mấu chốt của Julia nhưng không có bài hướng dẫn nào nhấn mạnh đủ vào cách suy nghĩ như một lập trình viên.

Tôi biết rằng cuốn sách Think Python của Allen Downey đã chứa tất cả những nguyên liệu quan trọng để học lập trình một cách bài bản. Tuy nhiên, cuốn sách này dựa trên ngôn ngữ lập trình Python. Bản nháp đầu tiên của tập bài giảng là một nồi lẩu thập cẩm tất cả các kiểu tài liệu tham khảo. Nhưng càng soạn thêm bài giảng, càng nhiều phần trở nên giống với các chương của cuốn Think Python. Ý tưởng phát triển tập bài giảng của tôi như một phiên bản chuyển từ Think Python sang Julia đã đơm hoa kết trái.

Tất cả những tư liệu đều có được dưới dạng các sổ tính Jupyter (notebooks) trong kho phần mềm GitHub. Sau khi tôi đăng một lời nhắn lên mục Julia của diễn đàn Discourse về tiến trình của khóa học này, những phản hồi thật vượt ngoài tưởng tượng. Một cuốn sách về những khái niệm lập trình cơ bản bằng Julia dường như là mắt xích bị thiếu trong môi trường Julia. Tôi đã liên hệ với Allen để xem liệu mình có thể bắt đầu viết một bản chuyển thể từ Think Python sang Julia không, và ông đã lập tức trả lời: “thực hiện thôi!” Ông đã giới thiệu thôi với biên tập viên của O'Reilly Media và bây giờ, sau một năm, tôi đang hoàn tất cuốn sách này.

Một chuyến đi bão táp. Tháng 8/2018 khi Julia phiên bản 1.0 được phát hành, cũng như tất cả đồng nghiệp lập trình viên Julia, tôi phải chuyển mã lệnh. Tất cả những ví dụ trong sách này đều được kiểm tra trong quá trình chuyển đổi các file mã nguồn sang dịnh dạng ASCIIDoc của nhà xuất bản. Cả chuỗi công cụ lẫn mã lệnh ví dụ, bản thân chúng phải được làm tương thích với Julia v1.0. Thật may là tôi không có lớp giảng đợt tháng 8 ... 

Hi vọng rằng bạn thích đọc cuốn này, và cũng hi vọng rằng nó giúp bạn lập trình và suy nghĩ như một nhà khoa học máy tính, hay ít nhất là được một phần như vậy.

_Ben Lauwens_

=== Tại sao lại là Julia?

Julia được phát hành lần dầu vào năm 2012 do nhóm tác giả Alan Edelman, Stefan Karpinski, Jeff Bezanson, và Viral Shah. Julia là ngôn ngữ lập trình miễn phí và có mã nguồn mở.

Việc chọn một ngôn ngữ lập trình không thể tránh khỏi ý kiến chủ quan. Theo tôi, những đặc điểm sau của Julia đã dẫn tới lựa chọn quyết định:

- Julia được phát triển như một ngôn ngữ lập trình hiệu năng cao.
- Julia sử dụng đa phương thức (multiple dispatch), bằng cách này cho phép lập trình viên chọn những dạng mẫu lập trình khác nhau phù hợp với ứng dụng.
- Julia là một ngôn ngữ định kiểu động mà ta dùng được bằng cách tương tác.
- Julia có một cú pháp cấp cao rất đẹp và dễ học.
- Julia là ngôn ngữ lập trình có tùy chọn định kiểu, theo đó những kiểu dữ liệu (người dùng định nghĩa) sẽ làm mã lệnh rõ ràng và mạnh hơn.
- Julia có một thư viện chuẩn rộng rãi và cũng có nhiều gói chương trình do bên thứ ba phát triển.

Julia là một ngôn ngữ lập trình duy nhất vì nó giải quyết vấn đề được gọi là "hai ngôn ngữ". Không cần ngôn ngữ lập trình nào khác để viết mã lệnh hiệu năng cao. Điều này không có nghĩa là tự nó có được. Lập trình viên phải chịu trách nhiệm tối ưu hóa mã lệnh tại đoạn nút thắt cổ chai, song công đoạn này lại có thể thực hiện bằng Julia.

=== Cuốn sách này dành cho ai?

Cuốn sách này được dành cho mọi người muốn học lập trình. Không cần biết trước bất cứ kiến thức bài bản nào.

Những khái niệm mới sẽ được giới thiệu dần và các chủ đề nâng cao sẽ được trình bày ở những chương sau.

Think Julia có thể dùng làm khóa học một kì cho các trường trung học hoặc cao đẳng, đại học giai đoạn đại cương.

=== Conventions Used in This Book

The following typographical conventions are used in this book:

_Italic_:: Indicates new terms, URLs, email addresses, filenames, and file extensions.

+Constant width+:: Used for program listings, as well as within paragraphs to refer to program elements such as variable or function names, databases, data types, environment variables, statements, and keywords.

**`Constant width bold`**:: Shows commands or other text that should be typed literally by the user.

_++Constant width italic++_:: Shows text that should be replaced with user-supplied values or by values determined by context.


[TIP]
====
This element signifies a tip or suggestion.
====

[NOTE]
====
This element signifies a general note.
====

[WARNING]
====
This element indicates a warning or caution.
====

=== Sử dụng các mã lệnh ví dụ

All code used in this book is available from a Git repository on GitHub: https://github.com/BenLauwens/ThinkJulia.jl. If you are not familiar with Git, it is a version control system that allows you to keep track of the files that make up a project. A collection of files under Git's control is called a “repository”. GitHub is a hosting service that provides storage for Git repositories and a convenient web interface.

A convenience package is provided that can be directly added to Julia. Just type *+pass:[add https://github.com/BenLauwens/ThinkJulia.jl]+* in the REPL in Pkg mode.

The easiest way to run Julia code is going to https://juliabox.com and start a free session. Both the REPL and a notebook interface are available. If you want to have Julia locally installed on you computer, JuliaPro from Julia Computing can be downloaded freely from https://juliacomputing.com/products/juliapro.html. It consists of a recent Julia version, the Juno IDE based on Atom and a number of preinstalled Julia packages. If you are more adventurous, you can download Julia from https://julialang.org, install the editor you like, e.g. Atom or Visual Studio Code, and activate the plugins for Julia integration. To a local install, you can also add the +IJulia+ package and run a Jupyter notebook on your computer.

This book is here to help you get your job done. In general, you may use example code in your programs and documentation. You do not need to contact us for permission unless you’re reproducing a significant portion of the code. For example, writing a program that uses several chunks of code from this book does not require permission. Selling or distributing a CD-ROM of examples from O’Reilly books does require permission. Answering a question by citing this book and quoting example code does not require permission. Incorporating a significant amount of example code from this book into your product’s documentation does require permission.

We appreciate, but do not require, attribution. An attribution usually includes the title, author, publisher, and ISBN. For example: “Think Julia by Ben Lauwens and Allen B; Downey (O’Reilly). Copyright 2019 Allen Downey, Ben Lauwens, 978-1-492-04503-8.”

If you feel your use of code examples falls outside fair use or the permission given above, feel free to contact us at pass:[<a class="email" href="mailto:permissions@oreilly.com"><em>permissions@oreilly.com</em></a>].

=== O'Reilly Safari

[role = "safarienabled"]
[NOTE]
====
pass:[<a href="http://oreilly.com/safari" class="orm:hideurl"><em class="hyperlink">Safari</em></a>] (formerly Safari Books Online) is a membership-based training and reference platform for enterprise, government, educators, and individuals.
====

Members have access to thousands of books, training videos, Learning Paths, interactive tutorials, and curated playlists from over 250 publishers, including O’Reilly Media, Harvard Business Review, Prentice Hall Professional, Addison-Wesley Professional, Microsoft Press, Sams, Que, Peachpit Press, Adobe, Focal Press, Cisco Press, John Wiley & Sons, Syngress, Morgan Kaufmann, IBM Redbooks, Packt, Adobe Press, FT Press, Apress, Manning, New Riders, McGraw-Hill, Jones & Bartlett, and Course Technology, among others.

For more information, please visit pass:[<a href="http://oreilly.com/safari" class="orm:hideurl"><em>http://oreilly.com/safari</em></a>]. 

=== Cách liên lạc với chúng tôi

Hãy dể lại những ý kiến góp ý và đặt câu hỏi liên quan đến nội dung sách cho nhà xuất bản:

++++
<ul class="simplelist">
  <li>O’Reilly Media, Inc.</li>
  <li>1005 Gravenstein Highway North</li>
  <li>Sebastopol, CA 95472</li>
  <li>800-998-9938 (ở Hoa Kỳ hoặc Canada)</li>
  <li>707-829-0515 (quốc tế hoặc nội địa)</li>
  <li>707-829-0104 (fax)</li>
</ul>
++++

Chúng tôi có một trang web cho cuốn sách này, trong đó có các đính chính, ví dụ và thông tin thêm. Bạn có thể truy cập trang đó theo đường link:$$http://oreilly.com/catalog/0636920215707$$[].

++++
<!--Đừng quên cập nhật đường link trên.-->
++++

Để bình luận hoặc đặt những câu hỏi hỏi kĩ thuật, hãy gửi email tới:[<a class="email" href="mailto:bookquestions@oreilly.com"><em>bookquestions@oreilly.com</em></a>].

Để biết thêm thông tin về những cuốn sách, khóa học, hội thảo và tin tức, hãy xem website của chúng tôi tại đường link:$$http://www.oreilly.com$$[].

Tìm chúng tôi trên Facebook: link:$$http://facebook.com/oreilly$$[]

Theo dõi chúng tôi trên Twitter: link:$$http://twitter.com/oreillymedia$$[]

Xem chúng tôi trên YouTube: link:$$http://www.youtube.com/oreillymedia$$[]

=== Lời cảm tạ

Thực lòng tôi muốn cám ơn Allen đã viết sách Think Python và cho phép tôi chuyển Think Python sang Julia. Sự tận tâm của ông thật có sức lan tỏa!

Tôi cũng muốn cám ơn những người hiệu đính kĩ thuật cho cuốn sách này, họ đã đóng góp nhiều ý kiến quý báu: Tim Besard, Bart Janssens và David P. Sanders.

Cám ơn Melissa Potter ở O'Reilly Media đã giúp cho cuốn sách này hay hơn. Cô đã buộc tôi phải soạn thảo đúng chuẩn và làm cuốn sách này giống nguyên bản ở mức sát nhất có thể.

Cám ơn Matt Hacker ở O'Reilly Media đã giúp tôi dùng chuỗi công cụ Atlas toolchain và một số vấn đề tô màu cú pháp.

Cám ơn toàn thể sinh viên đã đọc duyệt qua phiên bản đầu cuốn sách này cùng tất cả những người đóng góp (danh sách dưới đây) đã gửi những đính chính và gợi ý.

=== Danh sách những cá nhân đóng góp

Nếu bạn có một gợi ý hoặc đính chính, hãy gửi email tới ben.lauwens@gmail.com hoặc mở một issue trên GitHub. Nếu tôi thực hiện thay đổi theo phản hồi của bạn, tôi sẽ ghi tên bạn vào danh sách đóng góp (trừ khi bạn không muốn).

Hãy cho tôi biết phiên bản cuốn sách mà bạn muốn đề cập tới, và định dạng (PDF, web v.v.) Nếu bạn ghi cả một phần đoạn câu chứa lỗi thì sẽ tiện hơn nhiều để tôi tìm ra câu lỗi đó. Nếu ghi trang sách và số đề mục thì cũng được nhưng không tiện bằng. Cám ơn bạn!

[small]
--
- Scott Jones phát hiện thay đổi tên từ +Void+ thành +Nothing+ và điều này bắt đầu bước chuyển sang Julia v1.0.
- Robin Deits tìm thấy vài lỗi typo ở Chương 2.
- Mark Schmitz gợi ý cần bật tô màu cú pháp lên.
- Zigu Zhao phát hiện một số lỗi ở Chương 8.
- Oleg Soloviev phát hiện lỗi ở địa chỉ url để bổ sung gói +ThinkJulia+.
- Aaron Ang phát hiện vài vấn đề về đặt tên và vẽ hình (render).
- Sergey Volkov phát hiện một đường link sai trong Chương 7.
- Sean McAllister đề nghị nhắc tới một gói rất tốt là +BenchmarkTools+.
- Carlos Bolech gửi một danh sách dài các đính chính và gợi ý.
- Krishna Kumar sửa lại ví dụ Markov ở Chương 18.
--
